import { parseProject, grader } from "./src/index.ts";
import { ScratchProject } from "./src/scratch.ts";

const obj = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    name: "фон 1",
                    dataFormat: "svg",
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    name: "поп",
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Кот",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "A*GAo8Fs}w:~}zSI.jU6": {
                    opcode: "event_whenflagclicked",
                    next: ":OO-[*~7QQ[`|tE*T(:P",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 171,
                    y: 154,
                },
                ":OO-[*~7QQ[`|tE*T(:P": {
                    opcode: "control_repeat",
                    next: "MEa)cO+~%]6MhS:)wX.n",
                    parent: "A*GAo8Fs}w:~}zSI.jU6",
                    inputs: {
                        TIMES: [1, [6, "20"]],
                        SUBSTACK: [2, "c_|]T2SIA,lxXyxw!NUY"],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "c_|]T2SIA,lxXyxw!NUY": {
                    opcode: "control_create_clone_of",
                    next: "WpD00P)/_M,|@A6RYDLx",
                    parent: ":OO-[*~7QQ[`|tE*T(:P",
                    inputs: { CLONE_OPTION: [1, "/]kVieAeOOLfQ9iV.]}5"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "/]kVieAeOOLfQ9iV.]}5": {
                    opcode: "control_create_clone_of_menu",
                    next: null,
                    parent: "c_|]T2SIA,lxXyxw!NUY",
                    inputs: {},
                    fields: { CLONE_OPTION: ["_myself_", null] },
                    shadow: true,
                    topLevel: false,
                },
                "N@/O6xeO8)O*u1@CT|Ep": {
                    opcode: "control_forever",
                    next: null,
                    parent: ")SUSld8azsgG*ra9d(6i",
                    inputs: { SUBSTACK: [2, "(9_d^HsB7cbA},~95!R5"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "(9_d^HsB7cbA},~95!R5": {
                    opcode: "motion_changexby",
                    next: ")s^C6MkSn52AdfhsE?]Z",
                    parent: "N@/O6xeO8)O*u1@CT|Ep",
                    inputs: { DX: [3, "Xv?=sf:!MEpiX(/LkT+M", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                ")s^C6MkSn52AdfhsE?]Z": {
                    opcode: "motion_changeyby",
                    next: "^sWXt4UdfBOdFT/blHc;",
                    parent: "(9_d^HsB7cbA},~95!R5",
                    inputs: { DY: [3, "Pq?t97u{-O{5xQ$pj]em", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "WpD00P)/_M,|@A6RYDLx": {
                    opcode: "control_wait",
                    next: null,
                    parent: "c_|]T2SIA,lxXyxw!NUY",
                    inputs: { DURATION: [1, [5, "0.5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Xv?=sf:!MEpiX(/LkT+M": {
                    opcode: "operator_random",
                    next: null,
                    parent: "(9_d^HsB7cbA},~95!R5",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Pq?t97u{-O{5xQ$pj]em": {
                    opcode: "operator_random",
                    next: null,
                    parent: ")s^C6MkSn52AdfhsE?]Z",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                ")SUSld8azsgG*ra9d(6i": {
                    opcode: "looks_seteffectto",
                    next: "N@/O6xeO8)O*u1@CT|Ep",
                    parent: "MEa)cO+~%]6MhS:)wX.n",
                    inputs: { VALUE: [1, [4, "45"]] },
                    fields: { EFFECT: ["GHOST", null] },
                    shadow: false,
                    topLevel: false,
                },
                "?kGG3MfBxsX%RR`89)Tr": {
                    opcode: "procedures_definition",
                    next: "UddpnGZ}543stLhQ59Xa",
                    parent: null,
                    inputs: { custom_block: [1, "ZkUH=Og~isy4]YX3Ch_6"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 741,
                    y: 159,
                },
                "ZkUH=Og~isy4]YX3Ch_6": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "?kGG3MfBxsX%RR`89)Tr",
                    inputs: {
                        "o?e:.698Iu3={,:k_EqE": [1, "3bw7;hR)*n2ev4T-+x1b"],
                        "CyNnU/FH[7VpmBZ|%IYT": [1, "Ll;XTonYT.1^8:+FKZ5C"],
                    },
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "движение %s подпись %b",
                        argumentids:
                            '["o?e:.698Iu3={,:k_EqE","CyNnU/FH[7VpmBZ|%IYT"]',
                        argumentnames: '["число","логика"]',
                        argumentdefaults: '["","false"]',
                        warp: "false",
                    },
                },
                "MEa)cO+~%]6MhS:)wX.n": {
                    opcode: "procedures_call",
                    next: ")SUSld8azsgG*ra9d(6i",
                    parent: ":OO-[*~7QQ[`|tE*T(:P",
                    inputs: { "o?e:.698Iu3={,:k_EqE": [1, [10, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "движение %s подпись %b",
                        argumentids:
                            '["o?e:.698Iu3={,:k_EqE","CyNnU/FH[7VpmBZ|%IYT"]',
                        warp: "false",
                    },
                },
                "UddpnGZ}543stLhQ59Xa": {
                    opcode: "motion_turnright",
                    next: null,
                    parent: "?kGG3MfBxsX%RR`89)Tr",
                    inputs: { DEGREES: [3, "4Rv@N7Ze(*CCCJoyjZOL", [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "3bw7;hR)*n2ev4T-+x1b": {
                    opcode: "argument_reporter_string_number",
                    next: null,
                    parent: "ZkUH=Og~isy4]YX3Ch_6",
                    inputs: {},
                    fields: { VALUE: ["число", null] },
                    shadow: true,
                    topLevel: false,
                },
                "Ll;XTonYT.1^8:+FKZ5C": {
                    opcode: "argument_reporter_boolean",
                    next: null,
                    parent: "ZkUH=Og~isy4]YX3Ch_6",
                    inputs: {},
                    fields: { VALUE: ["логика", null] },
                    shadow: true,
                    topLevel: false,
                },
                "4Rv@N7Ze(*CCCJoyjZOL": {
                    opcode: "argument_reporter_string_number",
                    next: null,
                    parent: "UddpnGZ}543stLhQ59Xa",
                    inputs: {},
                    fields: { VALUE: ["число", null] },
                    shadow: false,
                    topLevel: false,
                },
                "^sWXt4UdfBOdFT/blHc;": {
                    opcode: "procedures_call",
                    next: "M7D9]f8J6O73v/GVc-T3",
                    parent: ")s^C6MkSn52AdfhsE?]Z",
                    inputs: { "o?e:.698Iu3={,:k_EqE": [1, [10, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "движение %s подпись %b",
                        argumentids:
                            '["o?e:.698Iu3={,:k_EqE","CyNnU/FH[7VpmBZ|%IYT"]',
                        warp: "false",
                    },
                },
                "M7D9]f8J6O73v/GVc-T3": {
                    opcode: "looks_seteffectto",
                    next: "50vV3@v3B2q*6XJ(OiH~",
                    parent: "^sWXt4UdfBOdFT/blHc;",
                    inputs: { VALUE: [1, [4, "45"]] },
                    fields: { EFFECT: ["GHOST", null] },
                    shadow: false,
                    topLevel: false,
                },
                "50vV3@v3B2q*6XJ(OiH~": {
                    opcode: "control_forever",
                    next: null,
                    parent: "M7D9]f8J6O73v/GVc-T3",
                    inputs: { SUBSTACK: [2, "R70G6@VMK{z`,3G@W2w$"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "R70G6@VMK{z`,3G@W2w$": {
                    opcode: "motion_changexby",
                    next: "9WIMh3nHEM+=e~23}YU}",
                    parent: "50vV3@v3B2q*6XJ(OiH~",
                    inputs: { DX: [3, "Y?TklwJ([ovgud9x8+Ta", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Y?TklwJ([ovgud9x8+Ta": {
                    opcode: "operator_random",
                    next: null,
                    parent: "R70G6@VMK{z`,3G@W2w$",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "9WIMh3nHEM+=e~23}YU}": {
                    opcode: "motion_changeyby",
                    next: null,
                    parent: "R70G6@VMK{z`,3G@W2w$",
                    inputs: { DY: [3, "9V#]aZR@Biq2u2AUB9Yd", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "9V#]aZR@Biq2u2AUB9Yd": {
                    opcode: "operator_random",
                    next: null,
                    parent: "9WIMh3nHEM+=e~23}YU}",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {
                "sk_Cvumi;vqOTHBrOSYV": {
                    blockId: "{Fr$t|0o4~64(%7=:/e1",
                    x: 959.9629669189453,
                    y: 167,
                    width: 200,
                    height: 200,
                    minimized: false,
                    text: "Случайные клоны",
                },
            },
            currentCostume: 0,
            costumes: [
                {
                    name: "костюм 1",
                    bitmapResolution: 1,
                    dataFormat: "svg",
                    assetId: "bcf454acf82e4504149f7ffe07081dbc",
                    md5ext: "bcf454acf82e4504149f7ffe07081dbc.svg",
                    rotationCenterX: 48,
                    rotationCenterY: 50,
                },
                {
                    name: "костюм 2",
                    bitmapResolution: 1,
                    dataFormat: "svg",
                    assetId: "0fb9be3e8397c983338cb71dc84d0b25",
                    md5ext: "0fb9be3e8397c983338cb71dc84d0b25.svg",
                    rotationCenterX: 46,
                    rotationCenterY: 53,
                },
            ],
            sounds: [
                {
                    name: "Мяу",
                    assetId: "83c36d806dc92327b9e7049a565c6bff",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 40681,
                    md5ext: "83c36d806dc92327b9e7049a565c6bff.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: -4.117647058823479,
            y: -3.17647058823529,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "2.1.14",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    },
};

const objNoParams = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    name: "фон 1",
                    dataFormat: "svg",
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    name: "поп",
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Кот",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "A*GAo8Fs}w:~}zSI.jU6": {
                    opcode: "event_whenflagclicked",
                    next: ":OO-[*~7QQ[`|tE*T(:P",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 176,
                    y: 154,
                },
                ":OO-[*~7QQ[`|tE*T(:P": {
                    opcode: "control_repeat",
                    next: "MEa)cO+~%]6MhS:)wX.n",
                    parent: "A*GAo8Fs}w:~}zSI.jU6",
                    inputs: {
                        TIMES: [1, [6, "20"]],
                        SUBSTACK: [2, "c_|]T2SIA,lxXyxw!NUY"],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "c_|]T2SIA,lxXyxw!NUY": {
                    opcode: "control_create_clone_of",
                    next: "WpD00P)/_M,|@A6RYDLx",
                    parent: ":OO-[*~7QQ[`|tE*T(:P",
                    inputs: { CLONE_OPTION: [1, "/]kVieAeOOLfQ9iV.]}5"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "/]kVieAeOOLfQ9iV.]}5": {
                    opcode: "control_create_clone_of_menu",
                    next: null,
                    parent: "c_|]T2SIA,lxXyxw!NUY",
                    inputs: {},
                    fields: { CLONE_OPTION: ["_myself_", null] },
                    shadow: true,
                    topLevel: false,
                },
                "N@/O6xeO8)O*u1@CT|Ep": {
                    opcode: "control_forever",
                    next: null,
                    parent: ")SUSld8azsgG*ra9d(6i",
                    inputs: { SUBSTACK: [2, "(9_d^HsB7cbA},~95!R5"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "(9_d^HsB7cbA},~95!R5": {
                    opcode: "motion_changexby",
                    next: ")s^C6MkSn52AdfhsE?]Z",
                    parent: "N@/O6xeO8)O*u1@CT|Ep",
                    inputs: { DX: [3, "Xv?=sf:!MEpiX(/LkT+M", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                ")s^C6MkSn52AdfhsE?]Z": {
                    opcode: "motion_changeyby",
                    next: null,
                    parent: "(9_d^HsB7cbA},~95!R5",
                    inputs: { DY: [3, "Pq?t97u{-O{5xQ$pj]em", [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "WpD00P)/_M,|@A6RYDLx": {
                    opcode: "control_wait",
                    next: null,
                    parent: "c_|]T2SIA,lxXyxw!NUY",
                    inputs: { DURATION: [1, [5, "0.5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Xv?=sf:!MEpiX(/LkT+M": {
                    opcode: "operator_random",
                    next: null,
                    parent: "(9_d^HsB7cbA},~95!R5",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Pq?t97u{-O{5xQ$pj]em": {
                    opcode: "operator_random",
                    next: null,
                    parent: ")s^C6MkSn52AdfhsE?]Z",
                    inputs: { FROM: [1, [4, "-5"]], TO: [1, [4, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                ")SUSld8azsgG*ra9d(6i": {
                    opcode: "looks_seteffectto",
                    next: "N@/O6xeO8)O*u1@CT|Ep",
                    parent: "MEa)cO+~%]6MhS:)wX.n",
                    inputs: { VALUE: [1, [4, "45"]] },
                    fields: { EFFECT: ["GHOST", null] },
                    shadow: false,
                    topLevel: false,
                },
                "?kGG3MfBxsX%RR`89)Tr": {
                    opcode: "procedures_definition",
                    next: "UddpnGZ}543stLhQ59Xa",
                    parent: null,
                    inputs: { custom_block: [1, "ZkUH=Og~isy4]YX3Ch_6"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 741,
                    y: 159,
                },
                "ZkUH=Og~isy4]YX3Ch_6": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "?kGG3MfBxsX%RR`89)Tr",
                    inputs: {
                        "o?e:.698Iu3={,:k_EqE": [
                            3,
                            null,
                            "3bw7;hR)*n2ev4T-+x1b",
                        ],
                        "CyNnU/FH[7VpmBZ|%IYT": [
                            3,
                            null,
                            "Ll;XTonYT.1^8:+FKZ5C",
                        ],
                    },
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "движение подпись",
                        argumentids: "[]",
                        argumentnames: "[]",
                        argumentdefaults: '["","false"]',
                        warp: "false",
                    },
                },
                "MEa)cO+~%]6MhS:)wX.n": {
                    opcode: "procedures_call",
                    next: ")SUSld8azsgG*ra9d(6i",
                    parent: ":OO-[*~7QQ[`|tE*T(:P",
                    inputs: { "o?e:.698Iu3={,:k_EqE": [3, null, [10, "5"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "движение подпись",
                        argumentids: "[]",
                        warp: "false",
                    },
                },
                "UddpnGZ}543stLhQ59Xa": {
                    opcode: "motion_turnright",
                    next: null,
                    parent: "?kGG3MfBxsX%RR`89)Tr",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "3bw7;hR)*n2ev4T-+x1b": {
                    opcode: "argument_reporter_string_number",
                    next: null,
                    parent: null,
                    inputs: {},
                    fields: { VALUE: ["число", null] },
                    shadow: true,
                    topLevel: true,
                    x: 933,
                    y: 163,
                },
                "Ll;XTonYT.1^8:+FKZ5C": {
                    opcode: "argument_reporter_boolean",
                    next: null,
                    parent: null,
                    inputs: {},
                    fields: { VALUE: ["логика", null] },
                    shadow: true,
                    topLevel: true,
                    x: 1077,
                    y: 163,
                },
            },
            comments: {
                "sk_Cvumi;vqOTHBrOSYV": {
                    blockId: "{Fr$t|0o4~64(%7=:/e1",
                    x: 959.9629669189453,
                    y: 167,
                    width: 200,
                    height: 200,
                    minimized: false,
                    text: "Случайные клоны",
                },
            },
            currentCostume: 0,
            costumes: [
                {
                    name: "костюм 1",
                    bitmapResolution: 1,
                    dataFormat: "svg",
                    assetId: "bcf454acf82e4504149f7ffe07081dbc",
                    md5ext: "bcf454acf82e4504149f7ffe07081dbc.svg",
                    rotationCenterX: 48,
                    rotationCenterY: 50,
                },
                {
                    name: "костюм 2",
                    bitmapResolution: 1,
                    dataFormat: "svg",
                    assetId: "0fb9be3e8397c983338cb71dc84d0b25",
                    md5ext: "0fb9be3e8397c983338cb71dc84d0b25.svg",
                    rotationCenterX: 46,
                    rotationCenterY: 53,
                },
            ],
            sounds: [
                {
                    name: "Мяу",
                    assetId: "83c36d806dc92327b9e7049a565c6bff",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 40681,
                    md5ext: "83c36d806dc92327b9e7049a565c6bff.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: -4.117647058823479,
            y: -3.17647058823529,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "2.1.14",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    },
};

const p = objNoParams as unknown;
const parsedP = parseProject(p as ScratchProject);

console.log(grader(parsedP));
