export const aliveBlocks = {
  targets: [
    {
      isStage: true,
      name: "Stage",
      variables: { "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0] },
      lists: {},
      broadcasts: {},
      blocks: {},
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          assetId: "cd21514d0531fdffb22204e0ec5ed84a",
          name: "фон 1",
          md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
          dataFormat: "svg",
          rotationCenterX: 240,
          rotationCenterY: 180,
        },
      ],
      sounds: [
        {
          assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
          name: "поп",
          dataFormat: "wav",
          format: "",
          rate: 48000,
          sampleCount: 1123,
          md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
        },
      ],
      volume: 100,
      layerOrder: 0,
      tempo: 60,
      videoTransparency: 50,
      videoState: "on",
      textToSpeechLanguage: null,
    },
    {
      isStage: false,
      name: "Спрайт 1",
      variables: {},
      lists: {},
      broadcasts: {},
      blocks: {
        "1?9fU3?-B[s}O%,:3ZEN": {
          opcode: "event_whenflagclicked",
          next: "B;glq6#c5Xh22b}[bt*Y",
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 162,
          y: 204,
        },
        "B;glq6#c5Xh22b}[bt*Y": {
          opcode: "control_if",
          next: null,
          parent: "1?9fU3?-B[s}O%,:3ZEN",
          inputs: {
            CONDITION: [2, "r+s1^O$y-6%p-$aK?_W1"],
            SUBSTACK: [2, "Y(vZ^murL!fc;HUu|V:A"],
          },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "r+s1^O$y-6%p-$aK?_W1": {
          opcode: "operator_gt",
          next: null,
          parent: "B;glq6#c5Xh22b}[bt*Y",
          inputs: { OPERAND1: [1, [10, "5"]], OPERAND2: [1, [10, "50"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "Y(vZ^murL!fc;HUu|V:A": {
          opcode: "motion_turnright",
          next: null,
          parent: "B;glq6#c5Xh22b}[bt*Y",
          inputs: { DEGREES: [1, [4, "15"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "@)tC(tiBJV8;QA)ciO!L": {
          opcode: "control_if",
          next: null,
          parent: null,
          inputs: {
            SUBSTACK: [2, "RwS^g?Woq3?*wKoOeSAK"],
            CONDITION: [2, "^Y!$BJsRyZTfV51vS|KV"],
          },
          fields: {},
          shadow: false,
          topLevel: true,
          x: 153,
          y: 509,
        },
        "RwS^g?Woq3?*wKoOeSAK": {
          opcode: "motion_gotoxy",
          next: "t=wIwSOMlY||^*x,fhw~",
          parent: "@)tC(tiBJV8;QA)ciO!L",
          inputs: { X: [1, [4, "0"]], Y: [1, [4, "0"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "t=wIwSOMlY||^*x,fhw~": {
          opcode: "motion_glideto",
          next: null,
          parent: "RwS^g?Woq3?*wKoOeSAK",
          inputs: { SECS: [1, [4, "1"]], TO: [1, "X`eahZ#}k)Dk9WG!6*vO"] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "X`eahZ#}k)Dk9WG!6*vO": {
          opcode: "motion_glideto_menu",
          next: null,
          parent: "t=wIwSOMlY||^*x,fhw~",
          inputs: {},
          fields: { TO: ["_random_", null] },
          shadow: true,
          topLevel: false,
        },
        "^Y!$BJsRyZTfV51vS|KV": {
          opcode: "operator_equals",
          next: null,
          parent: "@)tC(tiBJV8;QA)ciO!L",
          inputs: { OPERAND1: [1, [10, "4"]], OPERAND2: [1, [10, "50"]] },
          fields: {},
          shadow: false,
          topLevel: false,
        },
        "Int#0SK-``}TuR9Zj1kY": {
          opcode: "sound_stopallsounds",
          next: null,
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 636,
          y: 232,
        },
        ";C:ayf%[gA_-qAcW_cv/": {
          opcode: "event_whenthisspriteclicked",
          next: null,
          parent: null,
          inputs: {},
          fields: {},
          shadow: false,
          topLevel: true,
          x: 631,
          y: 555,
        },
      },
      comments: {},
      currentCostume: 0,
      costumes: [
        {
          assetId: "f8e72b8244738d0b448e46b38c5db6c2",
          name: "костюм 1",
          bitmapResolution: 1,
          md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
          dataFormat: "svg",
          rotationCenterX: 67,
          rotationCenterY: 95,
        },
        {
          assetId: "bb3a866c4db08353f6faf43c54990f10",
          name: "костюм 2",
          bitmapResolution: 1,
          md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
          dataFormat: "svg",
          rotationCenterX: 67,
          rotationCenterY: 95,
        },
        {
          assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
          name: "костюм 3",
          bitmapResolution: 1,
          md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
          dataFormat: "svg",
          rotationCenterX: 67,
          rotationCenterY: 95,
        },
        {
          assetId: "be2345a4417ff516f9c1a5ece86a8c64",
          name: "костюм 4",
          bitmapResolution: 1,
          md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
          dataFormat: "svg",
          rotationCenterX: 67,
          rotationCenterY: 95,
        },
      ],
      sounds: [
        {
          assetId: "28c76b6bebd04be1383fe9ba4933d263",
          name: "Beep",
          dataFormat: "wav",
          format: "",
          rate: 48000,
          sampleCount: 41517,
          md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
        },
      ],
      volume: 100,
      layerOrder: 1,
      visible: true,
      x: 0,
      y: 0,
      size: 100,
      direction: 90,
      draggable: false,
      rotationStyle: "all around",
    },
  ],
  monitors: [],
  extensions: [],
  meta: {
    semver: "3.0.0",
    vm: "0.2.0",
    agent:
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
  },
};
