export const customBlockNoUse = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "9=s^}fzaypv9QdjMoPB-": {
                    opcode: "event_whenflagclicked",
                    next: "Ch=yB@}[S./(-Qt3ZKx?",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 232,
                    y: -38,
                },
                "Ch=yB@}[S./(-Qt3ZKx?": {
                    opcode: "motion_movesteps",
                    next: null,
                    parent: "9=s^}fzaypv9QdjMoPB-",
                    inputs: { STEPS: [1, [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Gu*O1{mh]zv_R%o_kgTk": {
                    opcode: "procedures_definition",
                    next: "4b;WnmYp[+pNBCb//LOu",
                    parent: null,
                    inputs: { custom_block: [1, "E!|YDS2%/vD[*h,lVgvH"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 555,
                    y: -44,
                },
                "E!|YDS2%/vD[*h,lVgvH": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: {},
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        argumentnames: "[]",
                        argumentdefaults: "[]",
                        warp: "false",
                    },
                },
                "4b;WnmYp[+pNBCb//LOu": {
                    opcode: "motion_turnleft",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 0,
            y: 0,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};

export const customBlockUsed = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "9=s^}fzaypv9QdjMoPB-": {
                    opcode: "event_whenflagclicked",
                    next: "Ch=yB@}[S./(-Qt3ZKx?",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 209,
                    y: -51,
                },
                "Ch=yB@}[S./(-Qt3ZKx?": {
                    opcode: "motion_movesteps",
                    next: "UQ`U[li,.EiGz4=fv5Pz",
                    parent: "9=s^}fzaypv9QdjMoPB-",
                    inputs: { STEPS: [1, [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Gu*O1{mh]zv_R%o_kgTk": {
                    opcode: "procedures_definition",
                    next: "4b;WnmYp[+pNBCb//LOu",
                    parent: null,
                    inputs: { custom_block: [1, "E!|YDS2%/vD[*h,lVgvH"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 555,
                    y: -44,
                },
                "E!|YDS2%/vD[*h,lVgvH": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: {},
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        argumentnames: "[]",
                        argumentdefaults: "[]",
                        warp: "false",
                    },
                },
                "4b;WnmYp[+pNBCb//LOu": {
                    opcode: "motion_turnleft",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "UQ`U[li,.EiGz4=fv5Pz": {
                    opcode: "procedures_call",
                    next: null,
                    parent: "Ch=yB@}[S./(-Qt3ZKx?",
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        warp: "false",
                    },
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 0,
            y: 0,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};

export const clonesUsed = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "9=s^}fzaypv9QdjMoPB-": {
                    opcode: "event_whenflagclicked",
                    next: "Ch=yB@}[S./(-Qt3ZKx?",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 209,
                    y: -51,
                },
                "Ch=yB@}[S./(-Qt3ZKx?": {
                    opcode: "motion_movesteps",
                    next: "UQ`U[li,.EiGz4=fv5Pz",
                    parent: "9=s^}fzaypv9QdjMoPB-",
                    inputs: { STEPS: [1, [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Gu*O1{mh]zv_R%o_kgTk": {
                    opcode: "procedures_definition",
                    next: "4b;WnmYp[+pNBCb//LOu",
                    parent: null,
                    inputs: { custom_block: [1, "E!|YDS2%/vD[*h,lVgvH"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 555,
                    y: -44,
                },
                "E!|YDS2%/vD[*h,lVgvH": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: {},
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        argumentnames: "[]",
                        argumentdefaults: "[]",
                        warp: "false",
                    },
                },
                "4b;WnmYp[+pNBCb//LOu": {
                    opcode: "motion_turnleft",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "UQ`U[li,.EiGz4=fv5Pz": {
                    opcode: "procedures_call",
                    next: null,
                    parent: "Ch=yB@}[S./(-Qt3ZKx?",
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        warp: "false",
                    },
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 0,
            y: 0,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
        {
            isStage: false,
            name: "Anina Dance",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "w:1_vQ87[6^~qZpOA{Md": {
                    opcode: "event_whenthisspriteclicked",
                    next: "n54vzkZ/r-Qx)v.08;sO",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 78,
                    y: -55,
                },
                "n54vzkZ/r-Qx)v.08;sO": {
                    opcode: "control_create_clone_of",
                    next: null,
                    parent: "w:1_vQ87[6^~qZpOA{Md",
                    inputs: { CLONE_OPTION: [1, "]~{Eig(6_cYD]XB^z.,h"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "]~{Eig(6_cYD]XB^z.,h": {
                    opcode: "control_create_clone_of_menu",
                    next: null,
                    parent: "n54vzkZ/r-Qx)v.08;sO",
                    inputs: {},
                    fields: { CLONE_OPTION: ["_myself_", null] },
                    shadow: true,
                    topLevel: false,
                },
                ":[Ktuxh{#IR5=*K#8fk{": {
                    opcode: "control_start_as_clone",
                    next: "Bc^nMjqil3yb?5[6=$i(",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 444,
                    y: -47,
                },
                "Bc^nMjqil3yb?5[6=$i(": {
                    opcode: "motion_turnright",
                    next: null,
                    parent: ":[Ktuxh{#IR5=*K#8fk{",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "9374e067ca4b66427fc64a0822f6e468",
                    name: "anina stance",
                    bitmapResolution: 2,
                    md5ext: "9374e067ca4b66427fc64a0822f6e468.png",
                    dataFormat: "png",
                    rotationCenterX: 76,
                    rotationCenterY: 252,
                },
                {
                    assetId: "db6c03113f71b91f22a9f3351f90e5bf",
                    name: "anina top stand",
                    bitmapResolution: 2,
                    md5ext: "db6c03113f71b91f22a9f3351f90e5bf.png",
                    dataFormat: "png",
                    rotationCenterX: 74,
                    rotationCenterY: 280,
                },
                {
                    assetId: "2d208a34e74fdce9dab9d4c585dcfa2b",
                    name: "anina top R step",
                    bitmapResolution: 2,
                    md5ext: "2d208a34e74fdce9dab9d4c585dcfa2b.png",
                    dataFormat: "png",
                    rotationCenterX: 248,
                    rotationCenterY: 272,
                },
                {
                    assetId: "ed90e8b7a05c1552194af597ac0637cd",
                    name: "anina top L step",
                    bitmapResolution: 2,
                    md5ext: "ed90e8b7a05c1552194af597ac0637cd.png",
                    dataFormat: "png",
                    rotationCenterX: 228,
                    rotationCenterY: 274,
                },
                {
                    assetId: "a1c9b65dd07747964cce642f9099921b",
                    name: "anina top freeze",
                    bitmapResolution: 2,
                    md5ext: "a1c9b65dd07747964cce642f9099921b.png",
                    dataFormat: "png",
                    rotationCenterX: 110,
                    rotationCenterY: 268,
                },
                {
                    assetId: "f0d4dce1006cf447a0a4b53e0a8d0519",
                    name: "anina R cross",
                    bitmapResolution: 2,
                    md5ext: "f0d4dce1006cf447a0a4b53e0a8d0519.png",
                    dataFormat: "png",
                    rotationCenterX: 126,
                    rotationCenterY: 268,
                },
                {
                    assetId: "832a3ae650a1f3bede1e0c9f1779e535",
                    name: "anina pop front",
                    bitmapResolution: 2,
                    md5ext: "832a3ae650a1f3bede1e0c9f1779e535.png",
                    dataFormat: "png",
                    rotationCenterX: 68,
                    rotationCenterY: 270,
                },
                {
                    assetId: "e3698b76cb0864df2fbaba80e6bd8067",
                    name: "anina pop down",
                    bitmapResolution: 2,
                    md5ext: "e3698b76cb0864df2fbaba80e6bd8067.png",
                    dataFormat: "png",
                    rotationCenterX: 74,
                    rotationCenterY: 156,
                },
                {
                    assetId: "d86bb27b4f8d7b70c39c96f29c6943b4",
                    name: "anina pop left",
                    bitmapResolution: 2,
                    md5ext: "d86bb27b4f8d7b70c39c96f29c6943b4.png",
                    dataFormat: "png",
                    rotationCenterX: 238,
                    rotationCenterY: 266,
                },
                {
                    assetId: "7bb9c790b02231e1272701167c26b17a",
                    name: "anina pop right",
                    bitmapResolution: 2,
                    md5ext: "7bb9c790b02231e1272701167c26b17a.png",
                    dataFormat: "png",
                    rotationCenterX: 66,
                    rotationCenterY: 268,
                },
                {
                    assetId: "62c50c90535b64f2ae130a5c680ddcb4",
                    name: "anina pop L arm",
                    bitmapResolution: 2,
                    md5ext: "62c50c90535b64f2ae130a5c680ddcb4.png",
                    dataFormat: "png",
                    rotationCenterX: 68,
                    rotationCenterY: 274,
                },
                {
                    assetId: "105f4f3d260dcb8bea02ea9ee5d18cf4",
                    name: "anina pop stand",
                    bitmapResolution: 2,
                    md5ext: "105f4f3d260dcb8bea02ea9ee5d18cf4.png",
                    dataFormat: "png",
                    rotationCenterX: 76,
                    rotationCenterY: 276,
                },
                {
                    assetId: "eac2b5f7db5e81d00c43486179b8dcf8",
                    name: "anina pop R arm",
                    bitmapResolution: 2,
                    md5ext: "eac2b5f7db5e81d00c43486179b8dcf8.png",
                    dataFormat: "png",
                    rotationCenterX: 88,
                    rotationCenterY: 272,
                },
            ],
            sounds: [
                {
                    assetId: "0edb8fb88af19e6e17d0f8cf64c1d136",
                    name: "dance celebrate",
                    dataFormat: "wav",
                    format: "adpcm",
                    rate: 22050,
                    sampleCount: 176785,
                    md5ext: "0edb8fb88af19e6e17d0f8cf64c1d136.wav",
                },
            ],
            volume: 100,
            layerOrder: 2,
            visible: true,
            x: 16,
            y: 13,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};

export const customBlockWithParams = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "9=s^}fzaypv9QdjMoPB-": {
                    opcode: "event_whenflagclicked",
                    next: "Ch=yB@}[S./(-Qt3ZKx?",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 208,
                    y: -51,
                },
                "Ch=yB@}[S./(-Qt3ZKx?": {
                    opcode: "motion_movesteps",
                    next: "UQ`U[li,.EiGz4=fv5Pz",
                    parent: "9=s^}fzaypv9QdjMoPB-",
                    inputs: { STEPS: [1, [4, "10"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "Gu*O1{mh]zv_R%o_kgTk": {
                    opcode: "procedures_definition",
                    next: "4b;WnmYp[+pNBCb//LOu",
                    parent: null,
                    inputs: { custom_block: [1, "E!|YDS2%/vD[*h,lVgvH"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 555,
                    y: -43,
                },
                "E!|YDS2%/vD[*h,lVgvH": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: {},
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        argumentnames: "[]",
                        argumentdefaults: "[]",
                        warp: "false",
                    },
                },
                "4b;WnmYp[+pNBCb//LOu": {
                    opcode: "motion_turnleft",
                    next: null,
                    parent: "Gu*O1{mh]zv_R%o_kgTk",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "UQ`U[li,.EiGz4=fv5Pz": {
                    opcode: "procedures_call",
                    next: null,
                    parent: "Ch=yB@}[S./(-Qt3ZKx?",
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "название блока",
                        argumentids: "[]",
                        warp: "false",
                    },
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 0,
            y: 0,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
        {
            isStage: false,
            name: "Anina Dance",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "w:1_vQ87[6^~qZpOA{Md": {
                    opcode: "event_whenthisspriteclicked",
                    next: "n54vzkZ/r-Qx)v.08;sO",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 78,
                    y: -55,
                },
                "n54vzkZ/r-Qx)v.08;sO": {
                    opcode: "control_create_clone_of",
                    next: null,
                    parent: "w:1_vQ87[6^~qZpOA{Md",
                    inputs: { CLONE_OPTION: [1, "]~{Eig(6_cYD]XB^z.,h"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "]~{Eig(6_cYD]XB^z.,h": {
                    opcode: "control_create_clone_of_menu",
                    next: null,
                    parent: "n54vzkZ/r-Qx)v.08;sO",
                    inputs: {},
                    fields: { CLONE_OPTION: ["_myself_", null] },
                    shadow: true,
                    topLevel: false,
                },
                ":[Ktuxh{#IR5=*K#8fk{": {
                    opcode: "control_start_as_clone",
                    next: "Bc^nMjqil3yb?5[6=$i(",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 444,
                    y: -47,
                },
                "Bc^nMjqil3yb?5[6=$i(": {
                    opcode: "motion_turnright",
                    next: null,
                    parent: ":[Ktuxh{#IR5=*K#8fk{",
                    inputs: { DEGREES: [1, [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "9374e067ca4b66427fc64a0822f6e468",
                    name: "anina stance",
                    bitmapResolution: 2,
                    md5ext: "9374e067ca4b66427fc64a0822f6e468.png",
                    dataFormat: "png",
                    rotationCenterX: 76,
                    rotationCenterY: 252,
                },
                {
                    assetId: "db6c03113f71b91f22a9f3351f90e5bf",
                    name: "anina top stand",
                    bitmapResolution: 2,
                    md5ext: "db6c03113f71b91f22a9f3351f90e5bf.png",
                    dataFormat: "png",
                    rotationCenterX: 74,
                    rotationCenterY: 280,
                },
                {
                    assetId: "2d208a34e74fdce9dab9d4c585dcfa2b",
                    name: "anina top R step",
                    bitmapResolution: 2,
                    md5ext: "2d208a34e74fdce9dab9d4c585dcfa2b.png",
                    dataFormat: "png",
                    rotationCenterX: 248,
                    rotationCenterY: 272,
                },
                {
                    assetId: "ed90e8b7a05c1552194af597ac0637cd",
                    name: "anina top L step",
                    bitmapResolution: 2,
                    md5ext: "ed90e8b7a05c1552194af597ac0637cd.png",
                    dataFormat: "png",
                    rotationCenterX: 228,
                    rotationCenterY: 274,
                },
                {
                    assetId: "a1c9b65dd07747964cce642f9099921b",
                    name: "anina top freeze",
                    bitmapResolution: 2,
                    md5ext: "a1c9b65dd07747964cce642f9099921b.png",
                    dataFormat: "png",
                    rotationCenterX: 110,
                    rotationCenterY: 268,
                },
                {
                    assetId: "f0d4dce1006cf447a0a4b53e0a8d0519",
                    name: "anina R cross",
                    bitmapResolution: 2,
                    md5ext: "f0d4dce1006cf447a0a4b53e0a8d0519.png",
                    dataFormat: "png",
                    rotationCenterX: 126,
                    rotationCenterY: 268,
                },
                {
                    assetId: "832a3ae650a1f3bede1e0c9f1779e535",
                    name: "anina pop front",
                    bitmapResolution: 2,
                    md5ext: "832a3ae650a1f3bede1e0c9f1779e535.png",
                    dataFormat: "png",
                    rotationCenterX: 68,
                    rotationCenterY: 270,
                },
                {
                    assetId: "e3698b76cb0864df2fbaba80e6bd8067",
                    name: "anina pop down",
                    bitmapResolution: 2,
                    md5ext: "e3698b76cb0864df2fbaba80e6bd8067.png",
                    dataFormat: "png",
                    rotationCenterX: 74,
                    rotationCenterY: 156,
                },
                {
                    assetId: "d86bb27b4f8d7b70c39c96f29c6943b4",
                    name: "anina pop left",
                    bitmapResolution: 2,
                    md5ext: "d86bb27b4f8d7b70c39c96f29c6943b4.png",
                    dataFormat: "png",
                    rotationCenterX: 238,
                    rotationCenterY: 266,
                },
                {
                    assetId: "7bb9c790b02231e1272701167c26b17a",
                    name: "anina pop right",
                    bitmapResolution: 2,
                    md5ext: "7bb9c790b02231e1272701167c26b17a.png",
                    dataFormat: "png",
                    rotationCenterX: 66,
                    rotationCenterY: 268,
                },
                {
                    assetId: "62c50c90535b64f2ae130a5c680ddcb4",
                    name: "anina pop L arm",
                    bitmapResolution: 2,
                    md5ext: "62c50c90535b64f2ae130a5c680ddcb4.png",
                    dataFormat: "png",
                    rotationCenterX: 68,
                    rotationCenterY: 274,
                },
                {
                    assetId: "105f4f3d260dcb8bea02ea9ee5d18cf4",
                    name: "anina pop stand",
                    bitmapResolution: 2,
                    md5ext: "105f4f3d260dcb8bea02ea9ee5d18cf4.png",
                    dataFormat: "png",
                    rotationCenterX: 76,
                    rotationCenterY: 276,
                },
                {
                    assetId: "eac2b5f7db5e81d00c43486179b8dcf8",
                    name: "anina pop R arm",
                    bitmapResolution: 2,
                    md5ext: "eac2b5f7db5e81d00c43486179b8dcf8.png",
                    dataFormat: "png",
                    rotationCenterX: 88,
                    rotationCenterY: 272,
                },
            ],
            sounds: [
                {
                    assetId: "0edb8fb88af19e6e17d0f8cf64c1d136",
                    name: "dance celebrate",
                    dataFormat: "wav",
                    format: "adpcm",
                    rate: 22050,
                    sampleCount: 176785,
                    md5ext: "0edb8fb88af19e6e17d0f8cf64c1d136.wav",
                },
            ],
            volume: 100,
            layerOrder: 2,
            visible: true,
            x: 16,
            y: 13,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
        {
            isStage: false,
            name: "Andie",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "(]zYe?SvS~I1_.GvChGl": {
                    opcode: "event_whenkeypressed",
                    next: "zV@Uj0=WrkJ6)N)ajYBh",
                    parent: null,
                    inputs: {},
                    fields: { KEY_OPTION: ["space", null] },
                    shadow: false,
                    topLevel: true,
                    x: 35,
                    y: 21,
                },
                "0$/JPg@dH`g/3?w9%Pu[": {
                    opcode: "procedures_definition",
                    next: "])dPm,Jlo]gPL{W_0vPx",
                    parent: null,
                    inputs: { custom_block: [1, "pX8EQHY63=Qs:9k`M1!2"] },
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 453,
                    y: 42,
                },
                "pX8EQHY63=Qs:9k`M1!2": {
                    opcode: "procedures_prototype",
                    next: null,
                    parent: "0$/JPg@dH`g/3?w9%Pu[",
                    inputs: {
                        "T,)fFhh|I~9Jf0=bIkG7": [1, "a5T}6B~!dp|Mu5V!DK-E"],
                        "W`-:I,,K6y;;uJmb%N-v": [1, "?5t2fy/m0[iU$LUCya)/"],
                    },
                    fields: {},
                    shadow: true,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "params %s %b label text",
                        argumentids:
                            '["T,)fFhh|I~9Jf0=bIkG7","W`-:I,,K6y;;uJmb%N-v"]',
                        argumentnames: '["number or text","boolean"]',
                        argumentdefaults: '["","false"]',
                        warp: "false",
                    },
                },
                "a5T}6B~!dp|Mu5V!DK-E": {
                    opcode: "argument_reporter_string_number",
                    next: null,
                    parent: "pX8EQHY63=Qs:9k`M1!2",
                    inputs: {},
                    fields: { VALUE: ["number or text", null] },
                    shadow: true,
                    topLevel: false,
                },
                "?5t2fy/m0[iU$LUCya)/": {
                    opcode: "argument_reporter_boolean",
                    next: null,
                    parent: "pX8EQHY63=Qs:9k`M1!2",
                    inputs: {},
                    fields: { VALUE: ["boolean", null] },
                    shadow: true,
                    topLevel: false,
                },
                "])dPm,Jlo]gPL{W_0vPx": {
                    opcode: "motion_turnleft",
                    next: null,
                    parent: "0$/JPg@dH`g/3?w9%Pu[",
                    inputs: { DEGREES: [3, "}:-6AdP@Qth#M,csJC+s", [4, "15"]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "zV@Uj0=WrkJ6)N)ajYBh": {
                    opcode: "procedures_call",
                    next: null,
                    parent: "(]zYe?SvS~I1_.GvChGl",
                    inputs: {
                        "T,)fFhh|I~9Jf0=bIkG7": [1, [10, "4"]],
                        "W`-:I,,K6y;;uJmb%N-v": [2, "rurujG.sFBG)3s`1fgWp"],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                    mutation: {
                        tagName: "mutation",
                        children: [],
                        proccode: "params %s %b label text",
                        argumentids:
                            '["T,)fFhh|I~9Jf0=bIkG7","W`-:I,,K6y;;uJmb%N-v"]',
                        warp: "false",
                    },
                },
                "rurujG.sFBG)3s`1fgWp": {
                    opcode: "operator_gt",
                    next: null,
                    parent: "zV@Uj0=WrkJ6)N)ajYBh",
                    inputs: {
                        OPERAND1: [1, [10, "2"]],
                        OPERAND2: [1, [10, "50"]],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "}:-6AdP@Qth#M,csJC+s": {
                    opcode: "argument_reporter_string_number",
                    next: null,
                    parent: "])dPm,Jlo]gPL{W_0vPx",
                    inputs: {},
                    fields: { VALUE: ["number or text", null] },
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "afd293a0b27f25d656701c921eb8db0d",
                    name: "andie-a",
                    bitmapResolution: 1,
                    md5ext: "afd293a0b27f25d656701c921eb8db0d.svg",
                    dataFormat: "svg",
                    rotationCenterX: 86,
                    rotationCenterY: 77,
                },
                {
                    assetId: "63637df954fed242a50475accc7d6ec0",
                    name: "andie-b",
                    bitmapResolution: 1,
                    md5ext: "63637df954fed242a50475accc7d6ec0.svg",
                    dataFormat: "svg",
                    rotationCenterX: 46,
                    rotationCenterY: 77,
                },
                {
                    assetId: "6815fd7bb36a5955636024c7c70a29a6",
                    name: "andie-c",
                    bitmapResolution: 1,
                    md5ext: "6815fd7bb36a5955636024c7c70a29a6.svg",
                    dataFormat: "svg",
                    rotationCenterX: 52,
                    rotationCenterY: 36,
                },
                {
                    assetId: "57bc432bdfeed33ab316d751c9418c00",
                    name: "andie-d",
                    bitmapResolution: 1,
                    md5ext: "57bc432bdfeed33ab316d751c9418c00.svg",
                    dataFormat: "svg",
                    rotationCenterX: 86,
                    rotationCenterY: 43,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "pop",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 3,
            visible: true,
            x: 76,
            y: 15,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};
