export const emptyLoop = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "(+v@QAkt-S%o7#QfoQ#f": {
                    opcode: "event_whenflagclicked",
                    next: "X78%xr#zki#SeFXCI0)~",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 91,
                    y: -213,
                },
                "X78%xr#zki#SeFXCI0)~": {
                    opcode: "control_repeat",
                    next: null,
                    parent: "(+v@QAkt-S%o7#QfoQ#f",
                    inputs: { TIMES: [1, [6, ""]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 60.999999999999986,
            y: -25,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};
