export const emptyLoop = {
    targets: [
        {
            isStage: true,
            name: "Stage",
            variables: {
                "`jEk@4|i[#Fk?(8x)AV.-my variable": ["моя переменная", 0],
            },
            lists: {},
            broadcasts: {},
            blocks: {},
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "cd21514d0531fdffb22204e0ec5ed84a",
                    name: "фон 1",
                    md5ext: "cd21514d0531fdffb22204e0ec5ed84a.svg",
                    dataFormat: "svg",
                    rotationCenterX: 240,
                    rotationCenterY: 180,
                },
            ],
            sounds: [
                {
                    assetId: "83a9787d4cb6f3b7632b4ddfebf74367",
                    name: "поп",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 1123,
                    md5ext: "83a9787d4cb6f3b7632b4ddfebf74367.wav",
                },
            ],
            volume: 100,
            layerOrder: 0,
            tempo: 60,
            videoTransparency: 50,
            videoState: "on",
            textToSpeechLanguage: null,
        },
        {
            isStage: false,
            name: "Спрайт 1",
            variables: {},
            lists: {},
            broadcasts: {},
            blocks: {
                "(+v@QAkt-S%o7#QfoQ#f": {
                    opcode: "event_whenflagclicked",
                    next: "X78%xr#zki#SeFXCI0)~",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 226,
                    y: -161,
                },
                "X78%xr#zki#SeFXCI0)~": {
                    opcode: "control_repeat",
                    next: null,
                    parent: "(+v@QAkt-S%o7#QfoQ#f",
                    inputs: { TIMES: [1, [6, ""]] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "T_}rv$(c]!sbF2f-8Jm)": {
                    opcode: "event_whenflagclicked",
                    next: "EAdLUfN8~=-u1+_KJ_f2",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 226,
                    y: 61,
                },
                "EAdLUfN8~=-u1+_KJ_f2": {
                    opcode: "control_repeat",
                    next: null,
                    parent: "T_}rv$(c]!sbF2f-8Jm)",
                    inputs: {
                        TIMES: [1, [6, "10"]],
                        SUBSTACK: [2, "?x+nd90.fI4DLVjpWP{U"],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "VG}*k%{IT[e63wn(!HFA": {
                    opcode: "event_whenflagclicked",
                    next: "n/jAp_=EGaTM6.1y-OrK",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 226,
                    y: 302,
                },
                "n/jAp_=EGaTM6.1y-OrK": {
                    opcode: "control_repeat_until",
                    next: null,
                    parent: "VG}*k%{IT[e63wn(!HFA",
                    inputs: { CONDITION: [2, "+mZ+4pC^U^R2pYW8x2M)"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "}caOKKGQcA90n+}an82L": {
                    opcode: "event_whenflagclicked",
                    next: "?w3DgT-OHg=I*J6QD4N|",
                    parent: null,
                    inputs: {},
                    fields: {},
                    shadow: false,
                    topLevel: true,
                    x: 224,
                    y: 522,
                },
                "?w3DgT-OHg=I*J6QD4N|": {
                    opcode: "control_repeat_until",
                    next: null,
                    parent: "}caOKKGQcA90n+}an82L",
                    inputs: {
                        CONDITION: [2, "DC)U=k{jTj7oF`s)!+Up"],
                        SUBSTACK: [2, "_V422/]gx@^yM~9njwCz"],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "+mZ+4pC^U^R2pYW8x2M)": {
                    opcode: "operator_lt",
                    next: null,
                    parent: "n/jAp_=EGaTM6.1y-OrK",
                    inputs: {
                        OPERAND1: [1, [10, "3"]],
                        OPERAND2: [1, [10, "50"]],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "DC)U=k{jTj7oF`s)!+Up": {
                    opcode: "operator_lt",
                    next: null,
                    parent: "?w3DgT-OHg=I*J6QD4N|",
                    inputs: {
                        OPERAND1: [1, [10, "3"]],
                        OPERAND2: [1, [10, "50"]],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "_V422/]gx@^yM~9njwCz": {
                    opcode: "looks_sayforsecs",
                    next: null,
                    parent: "?w3DgT-OHg=I*J6QD4N|",
                    inputs: {
                        MESSAGE: [1, [10, "Привет!"]],
                        SECS: [1, [4, "2"]],
                    },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "?x+nd90.fI4DLVjpWP{U": {
                    opcode: "looks_switchcostumeto",
                    next: null,
                    parent: "EAdLUfN8~=-u1+_KJ_f2",
                    inputs: { COSTUME: [1, "lsI(g}lNTZG^}jd.+m+w"] },
                    fields: {},
                    shadow: false,
                    topLevel: false,
                },
                "lsI(g}lNTZG^}jd.+m+w": {
                    opcode: "looks_costume",
                    next: null,
                    parent: "?x+nd90.fI4DLVjpWP{U",
                    inputs: {},
                    fields: { COSTUME: ["костюм 1", null] },
                    shadow: true,
                    topLevel: false,
                },
            },
            comments: {},
            currentCostume: 0,
            costumes: [
                {
                    assetId: "f8e72b8244738d0b448e46b38c5db6c2",
                    name: "костюм 1",
                    bitmapResolution: 1,
                    md5ext: "f8e72b8244738d0b448e46b38c5db6c2.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb3a866c4db08353f6faf43c54990f10",
                    name: "костюм 2",
                    bitmapResolution: 1,
                    md5ext: "bb3a866c4db08353f6faf43c54990f10.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "bb6b82c9fa7c432c552ca2f251ae2078",
                    name: "костюм 3",
                    bitmapResolution: 1,
                    md5ext: "bb6b82c9fa7c432c552ca2f251ae2078.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
                {
                    assetId: "be2345a4417ff516f9c1a5ece86a8c64",
                    name: "костюм 4",
                    bitmapResolution: 1,
                    md5ext: "be2345a4417ff516f9c1a5ece86a8c64.svg",
                    dataFormat: "svg",
                    rotationCenterX: 67,
                    rotationCenterY: 95,
                },
            ],
            sounds: [
                {
                    assetId: "28c76b6bebd04be1383fe9ba4933d263",
                    name: "Beep",
                    dataFormat: "wav",
                    format: "",
                    rate: 48000,
                    sampleCount: 41517,
                    md5ext: "28c76b6bebd04be1383fe9ba4933d263.wav",
                },
            ],
            volume: 100,
            layerOrder: 1,
            visible: true,
            x: 60.999999999999986,
            y: -25,
            size: 100,
            direction: 90,
            draggable: false,
            rotationStyle: "all around",
        },
    ],
    monitors: [],
    extensions: [],
    meta: {
        semver: "3.0.0",
        vm: "0.2.0",
        agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    },
};
